let year=0,nextId=1,selectedId=null,selectedRole=null,history=[],lastKinChange=0;
function rate(age){if(age===6)return.2;if(age===13)return.4;if(age===20)return.6;if(age===27)return.8;return 1}
function current(p){const r=rate(p.age);return Object.fromEntries(STATS.map(s=>[s,Math.round(p.maxStats[s]*r)]))}
function level(p){return Math.round(avg(current(p)))}
function personality(p){const r=rank(p.maxStats);return`${HIGH[r[0]]}。${HIGH[r[1]]}。一方で、${LOW[r[5]]}うえ、${LOW[r[6]]}。`}
function makeStats(base){return Object.fromEntries(STATS.map(s=>[s,Math.max(1,Math.round(base*(.5+Math.random())))]))}
function makeSkills(stats,id){const r=rank(stats),src=[r[0],r[0],r[1],r[2],r[3]],used=new Set();return src.map((s,i)=>{const list=SKILLS[s];let n=(id*13+i*7)%list.length;while(used.has(list[n][0]))n=(n+1)%list.length;used.add(list[n][0]);return{name:list[n][0],effect:list[n][1],stat:s}})}
function body(){return{height:rand(150,177),bust:rand(76,108),waist:rand(54,72),hip:rand(80,108),hair:pick(HAIR)}}
function makePerson(age,base,origin,mother='—'){const id=nextId++,maxStats=makeStats(base);return{id,family:pick(FAMILY),given:pick(GIVEN),age,maxStats,body:body(),origin,mother,skills:makeSkills(maxStats,id)}}
function makeChild(m,g){const id=nextId++,maxStats={},inheritance={};STATS.forEach(s=>{const multiplier=.5+Math.random();inheritance[s]=multiplier;maxStats[s]=Math.max(1,Math.round(((m.maxStats[s]+g)/2)*multiplier))});return{id,family:m.family,given:pick(GIVEN),age:0,maxStats,inheritance,body:{height:Math.round(m.body.height*.7+162*.3+rand(-6,6)),bust:Math.round(m.body.bust*.7+92*.3+rand(-7,10)),waist:Math.round(m.body.waist*.7+60*.3+rand(-4,5)),hip:Math.round(m.body.hip*.7+94*.3+rand(-7,10)),hair:Math.random()<.7?m.body.hair:pick(HAIR)},origin:'神の娘・国家育成対象',mother:full(m),skills:makeSkills(maxStats,id)}}
function initial(){const out=[];AGES.forEach(age=>{for(let i=0;i<10;i++)out.push(makePerson(age,rand(18,38),age<20?'初期採用・仮巫女':'初期採用・正式巫女'))});return out}
let mikos=initial();
const kin={};
function ensureKin(family){if(!kin[family])kin[family]={children:0,adults:0,elderly:0,former:0,partners:0,births:0,deaths:0,marriages:0,migrations:0}}
mikos.forEach(p=>ensureKin(p.family));Object.keys(kin).forEach(f=>{const n=mikos.filter(p=>p.family===f).length;kin[f].children=n*rand(1,2);kin[f].adults=n*rand(2,4);kin[f].elderly=n*rand(0,2);kin[f].partners=Math.floor(n*.6)});
function kinPopulation(k){return k.children+k.adults+k.elderly+k.partners}
function totalKin(){return Object.values(kin).reduce((n,k)=>n+kinPopulation(k),0)}
function updateKin(retirees,departures){const before=totalKin();Object.values(kin).forEach(k=>{k.births=0;k.deaths=0;k.marriages=0;k.migrations=0});[...retirees,...departures].forEach(p=>{ensureKin(p.family);kin[p.family].former++;kin[p.family].adults++});const activeByFamily={};mikos.forEach(p=>activeByFamily[p.family]=(activeByFamily[p.family]||0)+1);Object.entries(kin).forEach(([family,k])=>{const active=activeByFamily[family]||0;const growToAdult=binomial(k.children,.32);k.children-=growToAdult;k.adults+=growToAdult;const growToElder=binomial(k.adults,.11);k.adults-=growToElder;k.elderly+=growToElder;const childDeaths=binomial(k.children,.004),adultDeaths=binomial(k.adults,.018),elderlyDeaths=binomial(k.elderly,.21);k.children-=childDeaths;k.adults-=adultDeaths;k.elderly-=elderlyDeaths;k.deaths=childDeaths+adultDeaths+elderlyDeaths;k.former=Math.min(k.former,k.adults);const marriagePool=Math.max(0,Math.floor(k.adults*.45)),marriages=binomial(marriagePool,.24);k.partners+=marriages;k.marriages=marriages;const ordinaryBirthPotential=Math.max(0,Math.floor((k.adults+k.partners)*.18)),births=binomial(ordinaryBirthPotential,.31)+binomial(active,.20);k.children+=births;k.births=births;const migrations=binomial(Math.max(0,k.adults+k.partners),.018),adultMigration=Math.min(k.adults,Math.ceil(migrations*.6)),partnerMigration=Math.min(k.partners,migrations-adultMigration);k.adults-=adultMigration;k.partners-=partnerMigration;k.former=Math.min(k.former,k.adults);k.migrations=adultMigration+partnerMigration});lastKinChange=totalKin()-before}
function assignments(){const workers=mikos.filter(p=>p.age>=13).map(p=>{const stats=current(p);return{person:p,stats,prefs:rank(stats),role:null}}),groups=Object.fromEntries(STATS.map(s=>[s,[]]));workers.forEach(w=>{w.role=w.prefs[0];groups[w.role].push(w)});let changed=true,safe=0;while(changed&&safe++<100){changed=false;for(const role of STATS){if(groups[role].length<=ROLE_LIMIT)continue;groups[role].sort((a,b)=>a.stats[role]-b.stats[role]);const overflow=groups[role].slice(0,groups[role].length-ROLE_LIMIT);for(const w of overflow){const dest=w.prefs.find(s=>s!==role&&groups[s].length<ROLE_LIMIT);if(!dest)continue;groups[role]=groups[role].filter(x=>x.person.id!==w.person.id);w.role=dest;groups[dest].push(w);changed=true}}}return{workers,groups}}
function roleOf(p){return assignments().workers.find(w=>w.person.id===p.id)?.role||null}
function reputation(){return Math.round(year*.25+mikos.filter(p=>p.age>=20).reduce((n,p)=>n+level(p),0)/30)}
function fameText(){const f=reputation();if(f<40)return'契約事業はまだ広く知られていない。';if(f<90)return'高待遇の国家特別職として近隣で評判になっている。';if(f<170)return'地方各地から優秀な志願者が集まる。';if(f<280)return'国内有数の人材育成事業として知られている。';return'国外の有力者からも志願希望が届いている。'}
function recruitLevel(){return Math.max(8,Math.min(80,Math.round(14+reputation()/8+rand(-14,14))))}
